# -*- coding: utf-8 -*-
"""Copy of DATA_SCIENCE_DATA_VISUALIZATION.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OI0PCpfB9WzFgvRIUI4m1Wz00efkwIdM
"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
import plotly.express as px

import pandas as pd
p="/content/drive/MyDrive/datas.csv"
d = pd.read_csv(p)
d.head()

d.info()

d.columns

d.describe()

# CHECKS FOR THE NULL VALUE. 
d.isnull().sum()

# CHECK FOR DIMENSIONALITY OF DATASET.
d.shape
# Return a tuple representing the dimensionality of the DataFrame.

da=d.head(20)
y=da["Job Title"]
x=da["Revenue"]
plt.rcParams['figure.figsize'] = [10,6]
plt.style.use("classic")
plt.scatter(x, y)
plt.title("AVERAGE SALARY FOR EACH JOB")
plt.show()

plt.rcParams["figure.figsize"] = (12,8)
plt.style.use("classic")
d["Company Name"].value_counts().head(10).plot.bar(color="pink")
plt.title("TOP 10 COMPANIES WITH HIGHEST NUMBER OF JOBS IN DATA SCIENCE",fontsize=18)
plt.xlabel("COMPANY NAME",fontsize=15)
plt.ylabel("NUMBER OF JOBS",fontsize=15)
plt.show()

plt.rcParams["figure.figsize"] = (12,8)
plt.style.use("classic")
y=d["Job Title"].value_counts().head(10)
da=d.head(10)
ml=da["Job Title"]
plt.title("NUMBER OF EMPLOYEES IN EACH SECTOR")
mylabels = ml

plt.pie(y, labels = mylabels)
plt.show()

da=d.head(10)
plt.rcParams["figure.figsize"] = (26,6)
plt.style.use("classic")
y=da["Job Title"]
x=da["Headquarters"]
colors = da["Location"]
plt.scatter(x, y, c="orange", cmap='viridis')
plt.colorbar()
plt.title("TOP 20 HEADQUARTERS OF DATA SCIENCE JOB HOLDER COMPANIES",fontsize=20)
plt.show()

da=d.head(10)
plt.rcParams["figure.figsize"] = (8,10)
plt.style.use("classic")
d["Founded"].value_counts().head(10).plot.bar(color="orange")
plt.title("NUMBER OF COMPANIES ESTABLISHED IN EACH YEAR",fontsize=20)
plt.xlabel("FOUNDATION YEAR",fontsize=14)
plt.ylabel("NUMBER OF COMPANIES",fontsize=14)
plt.show()
#plt.bar(x, y)
#plt.show()

plt.rcParams['figure.figsize'] = (12,8)
plt.style.use("classic")
d["Type of ownership"].value_counts().head(20).plot.bar(color="green")
plt.title("TYPES OF OWNERSHIP",fontsize=20)
plt.xlabel("OWNERSHIP",fontsize=14)
plt.ylabel("NUMBER OF COMPANIES",fontsize=14)
plt.show()

plt.rcParams['figure.figsize'] = (12,10)
plt.style.use("classic")
d["Rating"].value_counts().head(10)
x = d["Sector"].head(10)
plt.xlabel("RATING",fontsize=14)
plt.ylabel("DIFFERENT TYPES OF SECTOR",fontsize=14)
plt.title("RATING DIFFRENT TYPES OF SECTORS",fontsize=18)
plt.plot(x,"o-.m",ms=14)
plt.show()

plt.rcParams['figure.figsize'] = (10,10)
plt.style.use("classic")
x=d["Rating"].head(40)
plt.xlabel("RATING",fontsize=14)
plt.ylabel("NUMBER OF COMPANIES",fontsize=14)
plt.title("RATING OF THE COMPANIES",fontsize=18)
plt.hist(x)
plt.show()

